// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiE_oS5xCYP25kkhRam7jaF7_65wxi79c',
    appId: '1:115946982712:web:07b6b3244afb7af6cfc5cd',
    messagingSenderId: '115946982712',
    projectId: 'elderscareapp-1832d',
    authDomain: 'elderscareapp-1832d.firebaseapp.com',
    storageBucket: 'elderscareapp-1832d.appspot.com',
    measurementId: 'G-LR93483DP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqiGE99oWXk1hrcEfzD8VTfa8eNB5P_4w',
    appId: '1:115946982712:android:231ae4b6cfafb11ccfc5cd',
    messagingSenderId: '115946982712',
    projectId: 'elderscareapp-1832d',
    storageBucket: 'elderscareapp-1832d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvjcNMtQN8KCZBpXBQk7NdLLxTOJDhD9g',
    appId: '1:115946982712:ios:7598cdc47cf301c5cfc5cd',
    messagingSenderId: '115946982712',
    projectId: 'elderscareapp-1832d',
    storageBucket: 'elderscareapp-1832d.appspot.com',
    iosClientId: '115946982712-2p8kaigjnhrup6ur6ln37qb67gkolo9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.elderscareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvjcNMtQN8KCZBpXBQk7NdLLxTOJDhD9g',
    appId: '1:115946982712:ios:7598cdc47cf301c5cfc5cd',
    messagingSenderId: '115946982712',
    projectId: 'elderscareapp-1832d',
    storageBucket: 'elderscareapp-1832d.appspot.com',
    iosClientId: '115946982712-2p8kaigjnhrup6ur6ln37qb67gkolo9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.elderscareapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiE_oS5xCYP25kkhRam7jaF7_65wxi79c',
    appId: '1:115946982712:web:3f8cfed3cd20fadacfc5cd',
    messagingSenderId: '115946982712',
    projectId: 'elderscareapp-1832d',
    authDomain: 'elderscareapp-1832d.firebaseapp.com',
    storageBucket: 'elderscareapp-1832d.appspot.com',
    measurementId: 'G-GBQT2JTFW6',
  );

}